Igor/CategoriesModule
DmitryLorents/BookStore pull request #19
Opened 2023-12-07 19:14 UTC by Sacujo

Close #3

2023-12-07 19:32 UTC, DmitryLorents requested changes
Поправь комментарии плиз :)

2023-12-07 19:32 UTC, DmitryLorents commented on BookStore/Modules/CategoriesModule/Controller/CategoriesViewController.swift
> +            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: indexPath) as! CategoryCustomCell
перепиши на guard let ...as? Можешь в других контроллерах посмотреть

2023-12-07 19:32 UTC, DmitryLorents commented on BookStore/Modules/CategoriesModule/Controller/CategoriesViewController.swift
> +            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: indexPath) as! CategoryCustomCell
В самой ячейке создай static let reuseID = String(describing: CategoryCustomCell.self) и к нему тут обращайся

2023-12-07 19:32 UTC, DmitryLorents commented on BookStore/Modules/CategoriesModule/View/CategoriesView.swift
> +        layout.itemSize = CGSize(width: 165, height: 100)
Тут нужно привязаться к ширине экрана, чтобы помешалось ровно 2 ячейки за вычетом расстояний по бокам и по центру. Иначе эта вёрстка вся поплывёт. А выстоу задать множителем от ширины, чтобы сохранить пропорции из фигмы. А чтобы тебе привязаться к ширине экрана - надо это делать в деоегате контроллера

2023-12-08 07:56 UTC, Sacujo commented on BookStore/Modules/CategoriesModule/Controller/CategoriesViewController.swift
> +            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: indexPath) as! CategoryCustomCell
сделано

2023-12-08 08:15 UTC, DmitryLorents approved these changes
Ok

2023-12-08 08:22 UTC, DmitryLorents commented
Merged manually
Close https://github.com/DmitryLorents/BookStore/issues/3

2023-12-08 08:22 UTC, closed without merging